### ISSUE TITLE
Reading from Arrays

### ISSUE THREAD

**Issue by remexre** [skeeto/elisp-ffi#16]
Is there a good way to do this currently? If not, how does this look:

```c
int* get_foo(void);
```

```lisp
(setq ptr (ffi-call "libfoo.so" "get_foo" [:pointer]))
(ffi-read-offset :sint32 ptr 0)
(ffi-read-offset :sint32 ptr 4)
```

This should also allow resolving #6.

**EDIT**: Added types to read.

**Comment by skeeto** [comment]
Currently there's no way to do this. Your `ffi-read-offset` looks good, having both a type and a byte offset. I think I'd put the pointer argument first since it's what's being acted upon.

~~~el
(ffi-read-offset ptr :sint32 4)
~~~

Since this function is actually part of the API, I'd also give it a shorter name like `ffi-read` (or `ffi-load`? `ffi-deref`?) and rename the current `ffi-read`, which isn't really intended to be part of the public API.
