### ISSUE TITLE
Package

### ISSUE THREAD

**Issue by bersace** [skeeto/elisp-ffi#3]
Hi,

Do you intend to provide a package ?

Regards,
Étienne

**Comment by skeeto** [comment]
It's only at the proof-of-concept stage without any real plans to move
it forward at the moment. It needs support for accessing structs, fixes
to some allocation management issues across the interface (it leaks
everything right now), and trampoline support (callbacks). The latter
requires a change to the underlying protocol, since at the moment it's
fully synchronous with Emacs doing all the driving.

Furthermore since it requires that external binary, getting it into
Melpa is a bit more complicated. They're not comfortable distributing
binaries directly, so it needs to be set up to build from source if
possible, with a download fallback. See the EmacSQL ticket, for example:

https://github.com/milkypostman/melpa/pull/1458

It's more complicated here than with EmacSQL for a few reasons. One,
it's C++ which is slightly less likely to have a compiler around. It
would be easy to port to ANSI C, though. Second, it uses platform
specific calls (i.e. dlopen()), so portability is an issue. Third,
libffi doesn't embed a nicely like SQLite does, making the build more
complicated.

It's still all in the realm of possibility, though.

**Comment by bersace** [comment]
Thanks for the details. :)
