### ISSUE TITLE
Clarify docs about using structs

### ISSUE THREAD

**Issue by jjpe** [skeeto/elisp-ffi#6]
I'm looking at the `README.md` and read that `structs must be read raw`.
I also tried the `time` example listed there:

``` elisp
 ;; time(NULL);
(ffi-call nil "time" [:uint64 :pointer] nil)
;; => 1396496875
```

And while I do get a result that is incremented every second I'm still not sure how the `time` fn is handled since it is supposed to return a `time_t` struct, yet the return type here is marked as `uint64`. Could you clarify what you mean by `structs must be read raw`, and how to properly go about that?

**Comment by skeeto** [comment]
You know what? I completely neglected to add any way to dereference pointers! So in that sense there's been nothing to document. A few more bytecodes need to be added to address this.

To demonstrate how this would work right now, I'm going to call gettimeofday(), which take's two pointers.

~~~c
int gettimeofday(struct timeval *tv, struct timezone *tz);
~~~

The second argument will be NULL, so I won't worry about that. The first is a `struct timeval`, which looks like this:

~~~c
struct timeval {
    time_t      tv_sec;     /* seconds */
    suseconds_t tv_usec;    /* microseconds */
};
~~~

Don't be thrown off by the types (`time_t` and `suseconds_t`). On any modern system those are (and will forever be) just unsigned 64-bit ints. I need to allocate one of these, which I can eyeball as being 16 bytes. This is on a 64-bit system, where `size_t` (malloc()'s argument) is a 64-bit int.

~~~el
(setf tv (ffi-call nil "malloc" [:pointer :uint64] 16))
(ffi-call nil "memset" [:pointer :pointer :sint32 :uint64] tv 0 16)
~~~

The memset() isn't necessary, but I've got it here for demonstration purposes. Now pass that to gettimeofday().

~~~el
(ffi-call nil "gettimeofday" [:sint32 :pointer :pointer] tv 0)
~~~

Our memory now holds the time result. The problem is I can't actually derefence this. The FFI library still needs this capability added. For now I write a helper shared library with one function, u64_deref(). Pointer arithmetic in Elisp is another issue since it has tagged integers (not big enough to work on pointers), so instead of computing the offset in Elisp I've also added an offset argument.

~~~c
#include <stddef.h>
#include <stdint.h>

uint64_t u64_deref(void *v, size_t offset)
{
    return *(uint64_t *)((char *)v + offset);
}
~~~

Compile it:

    gcc -shared -FPIC -o deref.so deref.c

And now I can read my values. The microseconds field will be immediately following the seconds field, so it's offset by 8.

~~~el
;; Read seconds
(ffi-call "/tmp/deref.so" "u64_deref" [:uint64 :pointer :uint64] tv 0)
;; => 1430998779

;; Read microseconds
(ffi-call "/tmp/deref.so" "u64_deref" [:uint64 :pointer :uint64] tv 8)
;; => 978783
~~~

**Comment by jjpe** [comment]
Sorry it has taken so long to respond, I've been working with/at this, trying to get it to work.
Take a look at [this gist](https://gist.github.com/jjpe/96f33585d8986fceb0e5) of a test file I wrote that accesses the `ffi.h` API directly. Under Linux, this compiles for me, but the `ffi_call` call on line 88 makes it segfault. 
I wrote this test file because I've been having segfault issues with the emacs FFI (even on Linux when trying to implement dereferencing) and I think it has similar issues as this example.
